Add availabilityCheckerInterface to check sufficient variants in stock
BitBagCommerce/SyliusWishlistPlugin pull request #193
Opened 2023-02-24 12:04 UTC by Wojdylak

2023-02-24 12:26 UTC, mpysiak requested changes

2023-02-24 12:26 UTC, mpysiak commented on src/Command/Wishlist/AddProductsToCartInterface.php
> +
```suggestion
/*
 * This file has been created by developers from BitBag.
 * Feel free to contact us once you face any issues or want to start
 * You can find more information about us on https://bitbag.io and write us
 * an email on hello@bitbag.io.
 */
```

2023-02-24 12:54 UTC, mpysiak approved these changes

2023-02-24 13:24 UTC, lruozzi9 reviewed
This PR contains various BC on class AddProductsToCartHandler like adding a not nullable argument in the constructor and changing the argument interface of some methods...

2023-03-15 14:42 UTC, Wojdylak commented
@lruozzi9 Yes, you are right. I fixed the constructor, but I left the interfaces in private methods.

2023-03-16 07:54 UTC, mpysiak approved these changes

2023-03-16 07:54 UTC, mpysiak commented on src/CommandHandler/Wishlist/AddProductsToCartHandler.php
> +        if (null !== $this->availabilityChecker) {
you can merge these two if statements

2023-03-16 07:54 UTC, mpysiak commented on src/CommandHandler/Wishlist/AddProductsToCartHandler.php
> +        } elseif ($product->getVariant()->isInStock()) {
is elseif needed?

2023-03-16 08:08 UTC, merged