Fix the variant price json output
BitBagCommerce/SyliusWishlistPlugin pull request #226
Opened 2023-10-14 13:03 UTC by olimination

Fix the variant price json output for the data-bb-pricing html data attribute (#225)

2023-10-30 08:18 UTC, senghe requested changes

2023-10-30 08:18 UTC, senghe commented on src/Resources/views/WishlistDetails/_variantPrice.html.twig
> +                "{{ value }}"
We cannot just display the value, as there are i.e. arrays of CatalogPromotions etc.

2023-11-10 10:37 UTC, senghe commented
I see there is no change since my previous comment. I'm kindly closing this PR. Please open it when it'll be more current.

2023-11-10 10:37 UTC, closed without merging

2023-11-10 19:54 UTC, olimination commented
> I see there is no change since my previous comment. I'm kindly closing this PR. Please open it when it'll be more current.

Thanks @senghe for catching up. I was not able yet to check it any further. Hope to have some time soon. Will let you know if I have any updates on  this.