Fix doctrine migrations_paths order
BitBagCommerce/SyliusWishlistPlugin pull request #52
Opened 2021-04-21 22:29 UTC by piotrkardasz

Current plugin configuration `v1.5.3` override doctrine_migrations.migrations_paths order for project migration path like `App\Migrations:`

command `debug:config doctrine_migrations` returns
```yaml
doctrine_migrations:
    migrations_paths:
        BitBag\SyliusWishlistPlugin\Migrations: '@BitBagSyliusWishlistPlugin/Migrations'
        App\Migrations: /srv/sylius/src/Migrations
        Sylius\PayPalPlugin\Migrations: '@SyliusPayPalPlugin/Migrations'
        Sylius\Bundle\AdminApiBundle\Migrations: '@SyliusAdminApiBundle/Migrations'
        Sylius\Bundle\CoreBundle\Migrations: '@SyliusCoreBundle/Migrations'
```
should return:
```yaml
doctrine_migrations:
    migrations_paths:
        App\Migrations: /srv/sylius/src/Migrations
        BitBag\SyliusWishlistPlugin\Migrations: '@BitBagSyliusWishlistPlugin/Migrations'
        Sylius\PayPalPlugin\Migrations: '@SyliusPayPalPlugin/Migrations'
        Sylius\Bundle\AdminApiBundle\Migrations: '@SyliusAdminApiBundle/Migrations'
        Sylius\Bundle\CoreBundle\Migrations: '@SyliusCoreBundle/Migrations'

````

fixes #51

2021-04-21 23:34 UTC, pptasinski-bitbag commented
When i was updating this plugin i've taken invoice plugin tag 0.11.0 as pattern (https://github.com/Sylius/InvoicingPlugin/blob/v0.11.0/src/DependencyInjection/SyliusInvoicingExtension.php).

Please take a look - in the newest tag Sylius devs have different approach (https://github.com/Sylius/InvoicingPlugin/blob/v0.14.0/src/DependencyInjection/SyliusInvoicingExtension.php), maybe we should keep same convention? 

Also as i said during discussion - i think we should remove migrations from plugin. It will be easier to maintain it.

2021-04-21 23:34 UTC, pptasinski-bitbag requested changes
Please read my comment :)

2021-04-22 07:41 UTC, piotrkardasz commented
Fixed DI to use PrependDoctrineMigrationsTrait and now it resolving #52 issue.

2021-04-22 07:43 UTC, piotrkardasz commented
@pptasinski I strongly agree with You that we should discuss about migrations with the rest of the team.

2021-04-23 08:56 UTC, piotrkardasz commented
I added deprecation info for 2.0 that `Doctrine migrations existing in a bundle will be removed, move migrations to the project directory.`

2021-04-23 09:06 UTC, pptasinski-bitbag approved these changes

2021-04-23 09:06 UTC, merged